name: ShootingTest
version: '${project.version}'
main: net.teamuni.shootingtest.ShootingTest
api-version: 1.18
depend: [ GunsCore, Multiverse-Core, Citizens ]
commands:
  st:
    permission: st.manage
  dummy:
    permission: st.manage
permissions:
  st.manage:
    default: op